export const FETCH_GAMES = 'FETCH_GAMES'
export const NEW_GAME = 'NEW_GAME'
export const GET_GAME = 'GET_GAME'
export const DELETE_GAME = 'DELETE_GAME'

export const GET_GAMES_AND_TRANSFORM = 'GET_GAMES_AND_TRANSFORM'
export const GET_GAMES_IN_TIMESPAN = 'GET_GAMES_IN_TIMESPAN'

export const EDIT_GAME_INFO = 'EDIT_GAME_INFO'
export const LOCK_GAME_INFO = 'LOCK_GAME_INFO'
export const UNLOCK_GAME_INFO = 'UNLOCK_GAME_INFO'
export const RESET = 'RESET'


export const SHOW_UNAVAILABLE_MEMBERS = 'SHOW_UNAVAILABLE_MEMBERS'
export const HIDE_UNAVAILABLE_MEMBERS = 'HIDE_UNAVAILABLE_MEMBERS'
export const MAKE_MEMBER_AVAILABLE = 'MAKE_MEMBER_AVAILABLE'
export const ADD_NON_MEMBER = 'ADD_NON_MEMBER'
export const MAKE_MEMBER_UNAVAILABLE = 'MAKE_MEMBER_UNAVAILABLE'
export const MAKE_TEN_BUCKER_UNAVAILABLE = 'MAKE_TEN_BUCKER_UNAVAILABLE'
export const SHOW_NON_MEMBERS = 'SHOW_NON_MEMBERS'
export const HIDE_NON_MEMBERS = 'HIDE_NON_MEMBERS'

export const SHOW_FUTURE = "SHOW_FUTURE"
export const SHOW_PAST = "SHOW_PAST"

export const SHOW_TAB = "SHOW_TAB"
export const RESET_TABS = "RESET_TABS"

export const EDIT_FORM = "EDIT_FORM"
export const UPDATE_FIELD = "UPDATE_FIELD"

export const FETCH_PLAYERS = "FETCH_PLAYERS"
export const DELETE_PLAYER = "DELETE_PLAYER"
export const ADD_PLAYER = "ADD_PLAYER"
export const EDIT_PLAYER = "EDIT_PLAYER"

export const CREATE_GAME_ROSTER = "CREATE_GAME_ROSTER"

export const TRIGGER_PICK_MODE = "TRIGGER_PICK_MODE"
export const TRIGGER_DRAFT_MODE = "TRIGGER_DRAFT_MODE"
export const SET_PICK = 'SET_PICK'

export const SET_DATE_RANGE = "SET_DATE_RANGE"

export const SHOW_GAMES_TO_STATS = "SHOW_GAMES_TO_STATS"
export const SET_YEARS_VISIBILITIES = "SET_YEARS_VISIBILITIES"
export const ADD_GAME_TO_SELECTED = "ADD_GAME_TO_SELECTED"
export const REMOVE_GAME_FROM_SELECTED = "REMOVE_GAME_FROM_SELECTED"
export const ADD_PLAYER_TO_SELECTED = "ADD_PLAYER_TO_SELECTED"
export const REMOVE_PLAYER_FROM_SELECTED = "REMOVE_PLAYER_FROM_SELECTED"
export const TOGGLE_RECORDS_VIEWS = "TOGGLE_RECORDS_VIEWS"

export const ADD_PLAYER_RECORDS = "ADD_PLAYER_RECORDS"
export const REMOVE_PLAYER_RECORDS = "REMOVE_PLAYER_RECORDS"
export const REPLACE_PLAYERS_RECORDS = "REPLACE_PLAYERS_RECORDS"

export const SORT_AZ_ASC = "SORT_AZ_ASC"
export const SORT_AZ_DESC = "SORT_AZ_DESC"
export const SORT_GAMES_ASC = "SORT_GAMES_ASC"
export const SORT_GAMES_DESC = "SORT_GAMES_DESC"
export const SORT_WINS_ASC = "SORT_WINS_ASC"
export const SORT_WINS_DESC = "SORT_WINS_DESC"
export const SORT_GOALS_ASC = "SORT_GOALS_ASC"
export const SORT_GOALS_DESC = "SORT_GOALS_DESC"
export const SORT_GPG_ASC = "SORT_GPG_ASC"
export const SORT_GPG_DESC = "SORT_GPG_DESC"
export const SORT_ASSISTS_ASC = "SORT_ASSISTS_ASC"
export const SORT_ASSISTS_DESC = "SORT_ASSISTS_DESC"
export const SORT_APG_ASC = "SORT_APG_ASC"
export const SORT_APG_DESC = "SORT_APG_DESC"

// export const SET_CHART_DATA = "SET_CHART_DATA"
export const TOGGLE_SELECT_ALL = "TOGGLE_SELECT_ALL"
export const TOGGLE_POSITIONS = "TOGGLE_POSITIONS"

export const BATCH_CARD_UPDATE = "BATCH_CARD_UPDATE"
export const BATCH_CHART_UPDATE = "BATCH_CHART_UPDATE"
export const BATCH_UNSELECT = "BATCH_UNSELECT"

export const TOGGLE_PLAYER_MODAL = "TOGGLE_PLAYER_MODAL"
