export const FETCH_GAMES = 'FETCH_GAMES'
export const NEW_GAME = 'ADD_GAME'
export const GET_GAME = 'GET_GAME'
export const DELETE_GAME = 'DELETE_GAME'
export const EDIT_GAME_INFO = 'EDIT_GAME_INFO'
export const LOCK_GAME_INFO = 'LOCK_GAME_INFO'
export const UNLOCK_GAME_INFO = 'UNLOCK_GAME_INFO'


export const SHOW_UNAVAILABLE_MEMBERS = 'SHOW_UNAVAILABLE_MEMBERS'
export const SHOW_NON_MEMBERS = 'SHOW_NON_MEMBERS'
export const ADD_NON_MEMBER = 'ADD_NON_MEMBER'

export const SHOW_FUTURE = "SHOW_FUTURE"
export const SHOW_PAST = "SHOW_PAST"

export const SHOW_TAB = "SHOW_TAB"
export const RESET_TABS = "RESET_TABS"

export const EDIT_FORM = "EDIT_FORM"
export const UPDATE_FIELD = "UPDATE_FIELD"

export const FETCH_PLAYERS = "FETCH_PLAYERS"
export const DELETE_PLAYER = "DELETE_PLAYER"
export const ADD_PLAYER = "ADD_PLAYER"
export const EDIT_PLAYER = "EDIT_PLAYER"

export const CREATE_GAME_ROSTER = "CREATE_GAME_ROSTER"
